export const FirebaseEventTypes = {
    AUTH_FIREBASE_ANALYTICS_LOADED: "Auth Firebase analytics loaded",
    AUTH_FACEBOOK_REDIRECT: "Auth Facebook Redirect",
    AUTH_NEW_FACEBOOK_USER: "Auth New Facebook User",
    AUTH_CHANGE_USERNAME: "Auth Change Username",    
    AUTH_CHANGE_PHOTO_URL: "Auth Change PhotoUrl",
    AUTH_CHANGE_EMAIL: "Auth Change Email",
    AUTH_DELETE_ACCOUNT_INIT: "Auth Delete Account Init",
    AUTH_DELETE_ACCOUNT_FINAL: "Auth Delete Account Final",
    AUTH_DELETE_USER_ACCOUNT_ROLLBACK: "Auth Delete Account Rollback",
    AUTH_RESET_PASSWORD: "Auth Reset Password",
    AUTH_CREATE_APPLE_USER: "Auth Create Apple User",
    AUTH_SIGN_IN_APPLE_USER: "Auth Sign In Apple User",
    AUTH_SIGN_IN_FACEBOOK_USER: "Auth Sign In Facebook User",
    AUTH_SIGN_IN_NATIVE_FACEBOOK_USER: "Auth Sign In Native Facebook User",
    AUTH_SIGN_IN_BROWSWER_FACEBOOK_USER: "Auth Sign In Browser Facebook User",
    AUTH_SIGN_UP_USER: "Auth Sign Up User",
    AUTH_SIGN_IN_USER: "Auth Sign In User",
    AUTH_SIGN_OUT_USER: "Auth Sign Out User",
    AUTH_SIGN_IN_WITH_LINK_PASSWORD_RESET: "Auth Sign In With Link: Password Reset",
    AUTH_SIGN_IN_WITH_LINK_EMAIL_RESET: "Auth Sign In With Link: Email Reset",
    AUTH_SIGN_IN_WITH_LINK_DELETE_ACCOUNT: "Auth Sign In With Link: Delete Account",
    AUTH_SIGN_IN_WITH_LINK: "Auth Sign In With Link",
    AUTH_SIGN_IN_WITH_EMAIL_LINK: "Auth Sign In With Email Link",

    AUTH_ERROR_FACEBOOK_REDIRECT: "Auth Error Facebook Redirect",
    AUTH_ERROR_CHANGE_PHOTO_URL: "Auth Error Change Photo",
    AUTH_ERROR_CHANGE_EMAIL: "Auth Error Change Email",
    AUTH_ERROR_CHANGE_USERNAME: "Auth Error Change Username",
    AUTH_ERROR_DELETE_ACCOUNT_FINAL: "Auth Error Delete Account Final",
    AUTH_ERROR_RESET_PASSWORD: "Auth Error Reset Password",
    AUTH_ERROR_CREATE_APPLE_USER: "Auth Error Create Apple User",
    AUTH_ERROR_SIGN_IN_USER_APPLE_DEVICE: "Auth Error Sign In User Apple Device",
    AUTH_ERROR_SIGN_IN_USER_APPLE: "Auth Error Sign In User Apple",
    AUTH_ERROR_SIGN_IN_NATIVE_FACEBOOK_USER: "Auth Error Sign In Native Facebook User",
    AUTH_ERROR_SIGN_IN_BROWSER_FACEBOOK_USER: "Auth Error Sign In Browswer Facebook User",
    AUTH_ERROR_SIGN_UP_USER: "Auth Error Sign Up User",
    AUTH_ERROR_SIGN_IN_USER: "Auth Error Sign In User",
    AUTH_ERROR_SIGN_OUT_USER: "Auth Error Sign Out User",
    AUTH_ERROR_SIGN_IN_WITH_LINK: "Auth Error Sign In With Link",
    AUTH_ERROR_SIGN_IN_WITH_EMAIL_LINK: "Auth Error Sign In With Email Link",
    AUTH_ERROR_SIGN_UP_USER_SEND_EMAIL_VERIFCIATION: "Auth Error Sign Up User Send Email Verification",
}