options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1️⃣ Install dependencies
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm ci
        npm install -g @angular/cli@15

  # 2️⃣ Build Angular 15 app (production configuration)
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm run build -- --configuration=production

  # 3️⃣ Deploy to Firebase Hosting (using Google Cloud auth)
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g firebase-tools
        firebase deploy --only hosting --project $PROJECT_ID

# Set timeout to ensure sufficient build time
timeout: 1200s
